
# REVERSE PROXY ONLY WORKS WHEN THERE IS A DOMAIN
# server {
#     listen 443 ssl;
#     ssl_certificate /etc/nginx/ssl/poolreno.crt;
#     ssl_certificate_key /etc/nginx/ssl/poolreno.key;
#     server_name staging.poolreno.com;
#     location / {
#         root /var/www/deped/deped-app; # frontend
#         index index.htm index.html;
#         try_files $uri $uri/ /index.html;
#     }
#     location /api { # deped backend
#         root /var/www/deped/deped_backend/public;
#         index index.php index.html index.htm;
#         try_files $uri /index.php =404;
#         fastcgi_pass php-upstream;
#         fastcgi_index index.php;
#         fastcgi_buffers 16 16k;
#         fastcgi_buffer_size 32k;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         #fixes timeouts
#         fastcgi_read_timeout 600;
#         include fastcgi_params;
#     }
#     location /api/storage {
#         alias /var/www/deped/deped_backend/public/storage;
#     }
#     location ~ /\.ht {
#         deny all;
#     }
#     location /.well-known/acme-challenge/ {
#         root /var/www/letsencrypt/;
#         log_not_found off;
#     }
#     error_log /var/log/nginx/deped.error.log;
#     access_log /var/log/nginx/deped.access.log;
# }

server {
    listen 80;
    # For https
    # listen 443 ssl default_server;
    # listen [::]:443 ssl default_server ipv6only=on;
    # ssl_certificate /etc/nginx/ssl/default.crt;
    # ssl_certificate_key /etc/nginx/ssl/default.key;
    server_name 10.0.254.67;
    root /var/www/laravel-secure/public;
    index index.php index.html index.htm;
    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }
    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }
    location ~ /\.ht {
        deny all;
    }
    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
